import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1759137044048 implements MigrationInterface {
    name = 'Migration1759137044048'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` ADD \`price\` bigint NOT NULL DEFAULT '100000'`);
        await queryRunner.query(`ALTER TABLE \`order_receipt\` DROP FOREIGN KEY \`FK_6bcc142e76d004e355d733c99a0\``);
        await queryRunner.query(`ALTER TABLE \`order_receipt\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`conversation_participant\` DROP FOREIGN KEY \`FK_dd90174e375c888d7f431cf829e\``);
        await queryRunner.query(`ALTER TABLE \`conversation_participant\` DROP FOREIGN KEY \`FK_b1a75fd6cdb0ab0a82c5b01c34f\``);
        await queryRunner.query(`DROP INDEX \`IDX_497b032725751e1aad8a85832a\` ON \`conversation_participant\``);
        await queryRunner.query(`ALTER TABLE \`conversation_participant\` CHANGE \`active_at\` \`active_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`conversation_participant\` CHANGE \`inactive_at\` \`inactive_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`conversation_participant\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`conversation_participant\` CHANGE \`conversationId\` \`conversationId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP FOREIGN KEY \`FK_1fc3133b966bb83dc957188b712\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` CHANGE \`closed_at\` \`closed_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`conversations\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`message_attachments\` DROP FOREIGN KEY \`FK_5b4f24737fcb6b35ffdd4d16e13\``);
        await queryRunner.query(`ALTER TABLE \`message_attachments\` CHANGE \`audio_length\` \`audio_length\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`message_attachments\` CHANGE \`messageId\` \`messageId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_e5663ce0c730b2de83445e2fd19\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_2db9cf2b3ca111742793f6c37ce\``);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`content\` \`content\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`conversationId\` \`conversationId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`senderId\` \`senderId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` DROP FOREIGN KEY \`FK_68be5262b7406640f1be5115a77\``);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` DROP FOREIGN KEY \`FK_6a3f3eddd6087da229d01b8c360\``);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` DROP FOREIGN KEY \`FK_17f568239e3b87cab632c3f7761\``);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` CHANGE \`resize_page\` \`resize_page\` bigint NULL`);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` CHANGE \`file_size\` \`file_size\` bigint NULL`);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` CHANGE \`messageId\` \`messageId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` CHANGE \`orderEditId\` \`orderEditId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_edits\` DROP FOREIGN KEY \`FK_7c271f3f06495649cd7404ee2a7\``);
        await queryRunner.query(`ALTER TABLE \`order_edits\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_edit_pages\` DROP FOREIGN KEY \`FK_82006aae0534656baaef090ce9e\``);
        await queryRunner.query(`ALTER TABLE \`order_edit_pages\` CHANGE \`completed_at\` \`completed_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`order_edit_pages\` CHANGE \`orderEditId\` \`orderEditId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_pages\` DROP FOREIGN KEY \`FK_a84c556870d8dac48c3a725bec3\``);
        await queryRunner.query(`ALTER TABLE \`order_pages\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` DROP FOREIGN KEY \`FK_d5548982ea4b9918af86b32496e\``);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` DROP FOREIGN KEY \`FK_81c1107339f14b4fd8d807c08d6\``);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` DROP FOREIGN KEY \`FK_5f8431bc8f8d48bfdf9045adcfd\``);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` CHANGE \`editPageId\` \`editPageId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` CHANGE \`orderPageId\` \`orderPageId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_brief_attachments\` DROP FOREIGN KEY \`FK_4e5dc810a0b73080f5786e9ce4d\``);
        await queryRunner.query(`ALTER TABLE \`order_brief_attachments\` CHANGE \`audio_length\` \`audio_length\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_brief_attachments\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_692a909ee0fa9383e7859f9b406\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_fe1b8ba550e73f84ff228401aab\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`designer_profiles\` DROP FOREIGN KEY \`FK_147517de3d2ffce1a3daffcf6bc\``);
        await queryRunner.query(`ALTER TABLE \`designer_profiles\` DROP FOREIGN KEY \`FK_8169e8caaff9118647202e0a122\``);
        await queryRunner.query(`ALTER TABLE \`designer_profiles\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`designer_profiles\` CHANGE \`supervisorId\` \`supervisorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_assignments\` DROP FOREIGN KEY \`FK_be2c5ad5e40bd737781a9b6c2c4\``);
        await queryRunner.query(`ALTER TABLE \`order_assignments\` DROP FOREIGN KEY \`FK_714cf1a4b607de57389f65753fb\``);
        await queryRunner.query(`ALTER TABLE \`order_assignments\` CHANGE \`withdrawn_at\` \`withdrawn_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`order_assignments\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_assignments\` CHANGE \`designerId\` \`designerId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_reviews\` DROP FOREIGN KEY \`FK_2cc8a2bcd3d3b65009753b31596\``);
        await queryRunner.query(`ALTER TABLE \`order_reviews\` CHANGE \`comment\` \`comment\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`order_reviews\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_151b79a83ba240b0cb31b2302d1\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`design_assets\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`design_assets\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`design_preferences\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`design_preferences\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`design_samples\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`design_samples\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`delivery_date\` \`delivery_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`started_at\` \`started_at\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`commenced_at\` \`commenced_at\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`completed_at\` \`completed_at\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`last_edited_at\` \`last_edited_at\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`gender\` \`gender\` enum ('MALE', 'FEMALE') NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`reason\` \`reason\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`avatar\` \`avatar\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`telegram_handle\` \`telegram_handle\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`designer_applications\` CHANGE \`gender\` \`gender\` enum ('MALE', 'FEMALE') NULL`);
        await queryRunner.query(`ALTER TABLE \`designer_applications\` CHANGE \`avatar\` \`avatar\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`designer_applications\` CHANGE \`telegram_handle\` \`telegram_handle\` longtext NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_497b032725751e1aad8a85832a\` ON \`conversation_participant\` (\`conversationId\`, \`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`order_receipt\` ADD CONSTRAINT \`FK_6bcc142e76d004e355d733c99a0\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation_participant\` ADD CONSTRAINT \`FK_dd90174e375c888d7f431cf829e\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation_participant\` ADD CONSTRAINT \`FK_b1a75fd6cdb0ab0a82c5b01c34f\` FOREIGN KEY (\`conversationId\`) REFERENCES \`conversations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD CONSTRAINT \`FK_1fc3133b966bb83dc957188b712\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`message_attachments\` ADD CONSTRAINT \`FK_5b4f24737fcb6b35ffdd4d16e13\` FOREIGN KEY (\`messageId\`) REFERENCES \`messages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_e5663ce0c730b2de83445e2fd19\` FOREIGN KEY (\`conversationId\`) REFERENCES \`conversations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_2db9cf2b3ca111742793f6c37ce\` FOREIGN KEY (\`senderId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` ADD CONSTRAINT \`FK_68be5262b7406640f1be5115a77\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` ADD CONSTRAINT \`FK_6a3f3eddd6087da229d01b8c360\` FOREIGN KEY (\`messageId\`) REFERENCES \`messages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` ADD CONSTRAINT \`FK_17f568239e3b87cab632c3f7761\` FOREIGN KEY (\`orderEditId\`) REFERENCES \`order_edits\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_edits\` ADD CONSTRAINT \`FK_7c271f3f06495649cd7404ee2a7\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_edit_pages\` ADD CONSTRAINT \`FK_82006aae0534656baaef090ce9e\` FOREIGN KEY (\`orderEditId\`) REFERENCES \`order_edits\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_pages\` ADD CONSTRAINT \`FK_a84c556870d8dac48c3a725bec3\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` ADD CONSTRAINT \`FK_d5548982ea4b9918af86b32496e\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` ADD CONSTRAINT \`FK_81c1107339f14b4fd8d807c08d6\` FOREIGN KEY (\`editPageId\`) REFERENCES \`order_edit_pages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` ADD CONSTRAINT \`FK_5f8431bc8f8d48bfdf9045adcfd\` FOREIGN KEY (\`orderPageId\`) REFERENCES \`order_pages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_brief_attachments\` ADD CONSTRAINT \`FK_4e5dc810a0b73080f5786e9ce4d\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_692a909ee0fa9383e7859f9b406\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_fe1b8ba550e73f84ff228401aab\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`designer_profiles\` ADD CONSTRAINT \`FK_147517de3d2ffce1a3daffcf6bc\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`designer_profiles\` ADD CONSTRAINT \`FK_8169e8caaff9118647202e0a122\` FOREIGN KEY (\`supervisorId\`) REFERENCES \`designer_profiles\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_assignments\` ADD CONSTRAINT \`FK_be2c5ad5e40bd737781a9b6c2c4\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_assignments\` ADD CONSTRAINT \`FK_714cf1a4b607de57389f65753fb\` FOREIGN KEY (\`designerId\`) REFERENCES \`designer_profiles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_reviews\` ADD CONSTRAINT \`FK_2cc8a2bcd3d3b65009753b31596\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_151b79a83ba240b0cb31b2302d1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_151b79a83ba240b0cb31b2302d1\``);
        await queryRunner.query(`ALTER TABLE \`order_reviews\` DROP FOREIGN KEY \`FK_2cc8a2bcd3d3b65009753b31596\``);
        await queryRunner.query(`ALTER TABLE \`order_assignments\` DROP FOREIGN KEY \`FK_714cf1a4b607de57389f65753fb\``);
        await queryRunner.query(`ALTER TABLE \`order_assignments\` DROP FOREIGN KEY \`FK_be2c5ad5e40bd737781a9b6c2c4\``);
        await queryRunner.query(`ALTER TABLE \`designer_profiles\` DROP FOREIGN KEY \`FK_8169e8caaff9118647202e0a122\``);
        await queryRunner.query(`ALTER TABLE \`designer_profiles\` DROP FOREIGN KEY \`FK_147517de3d2ffce1a3daffcf6bc\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_fe1b8ba550e73f84ff228401aab\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_692a909ee0fa9383e7859f9b406\``);
        await queryRunner.query(`ALTER TABLE \`order_brief_attachments\` DROP FOREIGN KEY \`FK_4e5dc810a0b73080f5786e9ce4d\``);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` DROP FOREIGN KEY \`FK_5f8431bc8f8d48bfdf9045adcfd\``);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` DROP FOREIGN KEY \`FK_81c1107339f14b4fd8d807c08d6\``);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` DROP FOREIGN KEY \`FK_d5548982ea4b9918af86b32496e\``);
        await queryRunner.query(`ALTER TABLE \`order_pages\` DROP FOREIGN KEY \`FK_a84c556870d8dac48c3a725bec3\``);
        await queryRunner.query(`ALTER TABLE \`order_edit_pages\` DROP FOREIGN KEY \`FK_82006aae0534656baaef090ce9e\``);
        await queryRunner.query(`ALTER TABLE \`order_edits\` DROP FOREIGN KEY \`FK_7c271f3f06495649cd7404ee2a7\``);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` DROP FOREIGN KEY \`FK_17f568239e3b87cab632c3f7761\``);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` DROP FOREIGN KEY \`FK_6a3f3eddd6087da229d01b8c360\``);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` DROP FOREIGN KEY \`FK_68be5262b7406640f1be5115a77\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_2db9cf2b3ca111742793f6c37ce\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_e5663ce0c730b2de83445e2fd19\``);
        await queryRunner.query(`ALTER TABLE \`message_attachments\` DROP FOREIGN KEY \`FK_5b4f24737fcb6b35ffdd4d16e13\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP FOREIGN KEY \`FK_1fc3133b966bb83dc957188b712\``);
        await queryRunner.query(`ALTER TABLE \`conversation_participant\` DROP FOREIGN KEY \`FK_b1a75fd6cdb0ab0a82c5b01c34f\``);
        await queryRunner.query(`ALTER TABLE \`conversation_participant\` DROP FOREIGN KEY \`FK_dd90174e375c888d7f431cf829e\``);
        await queryRunner.query(`ALTER TABLE \`order_receipt\` DROP FOREIGN KEY \`FK_6bcc142e76d004e355d733c99a0\``);
        await queryRunner.query(`DROP INDEX \`IDX_497b032725751e1aad8a85832a\` ON \`conversation_participant\``);
        await queryRunner.query(`ALTER TABLE \`designer_applications\` CHANGE \`telegram_handle\` \`telegram_handle\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`designer_applications\` CHANGE \`avatar\` \`avatar\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`designer_applications\` CHANGE \`gender\` \`gender\` enum ('MALE', 'FEMALE') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`telegram_handle\` \`telegram_handle\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`avatar\` \`avatar\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`reason\` \`reason\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`gender\` \`gender\` enum ('MALE', 'FEMALE') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`userId\` \`userId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`last_edited_at\` \`last_edited_at\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`completed_at\` \`completed_at\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`commenced_at\` \`commenced_at\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`started_at\` \`started_at\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`delivery_date\` \`delivery_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`design_samples\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`design_samples\` longtext CHARACTER SET "utf8mb4" COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`design_preferences\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`design_preferences\` longtext CHARACTER SET "utf8mb4" COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`design_assets\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`design_assets\` longtext CHARACTER SET "utf8mb4" COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_151b79a83ba240b0cb31b2302d1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_reviews\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_reviews\` CHANGE \`comment\` \`comment\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_reviews\` ADD CONSTRAINT \`FK_2cc8a2bcd3d3b65009753b31596\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_assignments\` CHANGE \`designerId\` \`designerId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_assignments\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_assignments\` CHANGE \`withdrawn_at\` \`withdrawn_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_assignments\` ADD CONSTRAINT \`FK_714cf1a4b607de57389f65753fb\` FOREIGN KEY (\`designerId\`) REFERENCES \`designer_profiles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_assignments\` ADD CONSTRAINT \`FK_be2c5ad5e40bd737781a9b6c2c4\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`designer_profiles\` CHANGE \`supervisorId\` \`supervisorId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`designer_profiles\` CHANGE \`userId\` \`userId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`designer_profiles\` ADD CONSTRAINT \`FK_8169e8caaff9118647202e0a122\` FOREIGN KEY (\`supervisorId\`) REFERENCES \`designer_profiles\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`designer_profiles\` ADD CONSTRAINT \`FK_147517de3d2ffce1a3daffcf6bc\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`userId\` \`userId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_fe1b8ba550e73f84ff228401aab\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_692a909ee0fa9383e7859f9b406\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_brief_attachments\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_brief_attachments\` CHANGE \`audio_length\` \`audio_length\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_brief_attachments\` ADD CONSTRAINT \`FK_4e5dc810a0b73080f5786e9ce4d\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` CHANGE \`orderPageId\` \`orderPageId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` CHANGE \`editPageId\` \`editPageId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` ADD CONSTRAINT \`FK_5f8431bc8f8d48bfdf9045adcfd\` FOREIGN KEY (\`orderPageId\`) REFERENCES \`order_pages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` ADD CONSTRAINT \`FK_81c1107339f14b4fd8d807c08d6\` FOREIGN KEY (\`editPageId\`) REFERENCES \`order_edit_pages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` ADD CONSTRAINT \`FK_d5548982ea4b9918af86b32496e\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_pages\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_pages\` ADD CONSTRAINT \`FK_a84c556870d8dac48c3a725bec3\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_edit_pages\` CHANGE \`orderEditId\` \`orderEditId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_edit_pages\` CHANGE \`completed_at\` \`completed_at\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_edit_pages\` ADD CONSTRAINT \`FK_82006aae0534656baaef090ce9e\` FOREIGN KEY (\`orderEditId\`) REFERENCES \`order_edits\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_edits\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_edits\` ADD CONSTRAINT \`FK_7c271f3f06495649cd7404ee2a7\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` CHANGE \`orderEditId\` \`orderEditId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` CHANGE \`messageId\` \`messageId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` CHANGE \`file_size\` \`file_size\` bigint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` CHANGE \`resize_page\` \`resize_page\` bigint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` ADD CONSTRAINT \`FK_17f568239e3b87cab632c3f7761\` FOREIGN KEY (\`orderEditId\`) REFERENCES \`order_edits\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` ADD CONSTRAINT \`FK_6a3f3eddd6087da229d01b8c360\` FOREIGN KEY (\`messageId\`) REFERENCES \`messages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_submissions\` ADD CONSTRAINT \`FK_68be5262b7406640f1be5115a77\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`senderId\` \`senderId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`conversationId\` \`conversationId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`content\` \`content\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_2db9cf2b3ca111742793f6c37ce\` FOREIGN KEY (\`senderId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_e5663ce0c730b2de83445e2fd19\` FOREIGN KEY (\`conversationId\`) REFERENCES \`conversations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`message_attachments\` CHANGE \`messageId\` \`messageId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`message_attachments\` CHANGE \`audio_length\` \`audio_length\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`message_attachments\` ADD CONSTRAINT \`FK_5b4f24737fcb6b35ffdd4d16e13\` FOREIGN KEY (\`messageId\`) REFERENCES \`messages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversations\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`conversations\` CHANGE \`closed_at\` \`closed_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD CONSTRAINT \`FK_1fc3133b966bb83dc957188b712\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation_participant\` CHANGE \`conversationId\` \`conversationId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`conversation_participant\` CHANGE \`userId\` \`userId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`conversation_participant\` CHANGE \`inactive_at\` \`inactive_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`conversation_participant\` CHANGE \`active_at\` \`active_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_497b032725751e1aad8a85832a\` ON \`conversation_participant\` (\`conversationId\`, \`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`conversation_participant\` ADD CONSTRAINT \`FK_b1a75fd6cdb0ab0a82c5b01c34f\` FOREIGN KEY (\`conversationId\`) REFERENCES \`conversations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation_participant\` ADD CONSTRAINT \`FK_dd90174e375c888d7f431cf829e\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_receipt\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_receipt\` ADD CONSTRAINT \`FK_6bcc142e76d004e355d733c99a0\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_resize_extras\` DROP COLUMN \`price\``);
    }

}
